/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Apr 17 19:21:21 2025


#include "ColorRegionDetector_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(ColorRegionDetectorParamsCOMPONENT, "yarp.device.ColorRegionDetector")
}


ColorRegionDetector_ParamsParser::ColorRegionDetector_ParamsParser()
{
}


std::vector<std::string> ColorRegionDetector_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("algorithm");
    params.push_back("morphClosing");
    params.push_back("threshold");
    params.push_back("maxNumBlobs");
    return params;
}


bool      ColorRegionDetector_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(ColorRegionDetectorParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter algorithm
    {
        if (config.check("algorithm"))
        {
            m_algorithm = config.find("algorithm").asString();
            yCInfo(ColorRegionDetectorParamsCOMPONENT) << "Parameter 'algorithm' using value:" << m_algorithm;
        }
        else
        {
            yCInfo(ColorRegionDetectorParamsCOMPONENT) << "Parameter 'algorithm' using DEFAULT value:" << m_algorithm;
        }
        prop_check.unput("algorithm");
    }

    //Parser of parameter morphClosing
    {
        if (config.check("morphClosing"))
        {
            m_morphClosing = config.find("morphClosing").asFloat64();
            yCInfo(ColorRegionDetectorParamsCOMPONENT) << "Parameter 'morphClosing' using value:" << m_morphClosing;
        }
        else
        {
            yCInfo(ColorRegionDetectorParamsCOMPONENT) << "Parameter 'morphClosing' using DEFAULT value:" << m_morphClosing;
        }
        prop_check.unput("morphClosing");
    }

    //Parser of parameter threshold
    {
        if (config.check("threshold"))
        {
            m_threshold = config.find("threshold").asInt64();
            yCInfo(ColorRegionDetectorParamsCOMPONENT) << "Parameter 'threshold' using value:" << m_threshold;
        }
        else
        {
            yCInfo(ColorRegionDetectorParamsCOMPONENT) << "Parameter 'threshold' using DEFAULT value:" << m_threshold;
        }
        prop_check.unput("threshold");
    }

    //Parser of parameter maxNumBlobs
    {
        if (config.check("maxNumBlobs"))
        {
            m_maxNumBlobs = config.find("maxNumBlobs").asInt64();
            yCInfo(ColorRegionDetectorParamsCOMPONENT) << "Parameter 'maxNumBlobs' using value:" << m_maxNumBlobs;
        }
        else
        {
            yCInfo(ColorRegionDetectorParamsCOMPONENT) << "Parameter 'maxNumBlobs' using DEFAULT value:" << m_maxNumBlobs;
        }
        prop_check.unput("maxNumBlobs");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(ColorRegionDetectorParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(ColorRegionDetectorParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      ColorRegionDetector_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: ColorRegionDetector\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'algorithm': detection algorithm\n");
    doc = doc + std::string("'morphClosing': morphological closure\n");
    doc = doc + std::string("'threshold': binarization threshold\n");
    doc = doc + std::string("'maxNumBlobs': maximum number of blobs\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device ColorRegionDetector --algorithm blueMinusRed --morphClosing 2.0 --threshold 55 --maxNumBlobs 1\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device ColorRegionDetector\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
