/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Apr 17 19:21:21 2025


#include "ArucoDetector_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(ArucoDetectorParamsCOMPONENT, "yarp.device.ArucoDetector")
}


ArucoDetector_ParamsParser::ArucoDetector_ParamsParser()
{
}


std::vector<std::string> ArucoDetector_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("aruco_size");
    return params;
}


bool      ArucoDetector_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(ArucoDetectorParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter aruco_size
    {
        if (config.check("aruco_size"))
        {
            m_aruco_size = config.find("aruco_size").asString();
            yCInfo(ArucoDetectorParamsCOMPONENT) << "Parameter 'aruco_size' using value:" << m_aruco_size;
        }
        else
        {
            yCInfo(ArucoDetectorParamsCOMPONENT) << "Parameter 'aruco_size' using DEFAULT value:" << m_aruco_size;
        }
        prop_check.unput("aruco_size");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(ArucoDetectorParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(ArucoDetectorParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      ArucoDetector_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: ArucoDetector\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'aruco_size': ArUco code format\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device ArucoDetector --aruco_size ARUCO_ORIGINAL\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device ArucoDetector\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
