#ifndef __KINECT_FUSION_LOG_COMPONENT_HPP__
#define __KINECT_FUSION_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(KINFU)

#endif // __KINECT_FUSION_LOG_COMPONENT_HPP__
