/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Apr 17 19:21:21 2025


#ifndef HAARDETECTOR_PARAMSPARSER_H
#define HAARDETECTOR_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class HaarDetector.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value                   | Required | Description             | Notes |
* |:----------:|:--------------:|:------:|:-----:|:-------------------------------:|:--------:|:-----------------------:|:-----:|
* | -          | xmlCascade     | string | -     | haarcascade_frontalface_alt.xml | 0        | Haar cascade model file | -     |
* | -          | lbfModel       | string | -     | lbfmodel/lbfmodel.yaml          | 0        | LBF model file          | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device HaarDetector --xmlCascade haarcascade_frontalface_alt.xml --lbfModel lbfmodel/lbfmodel.yaml
* \endcode
*
* \code{.unparsed}
* yarpdev --device HaarDetector
* \endcode
*
*/

class HaarDetector_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    HaarDetector_ParamsParser();
    ~HaarDetector_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"HaarDetector"};
    const std::string m_device_name = {"HaarDetector"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 1;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    const std::string m_xmlCascade_defaultValue = {"haarcascade_frontalface_alt.xml"};
    const std::string m_lbfModel_defaultValue = {"lbfmodel/lbfmodel.yaml"};

    std::string m_xmlCascade = {"haarcascade_frontalface_alt.xml"};
    std::string m_lbfModel = {"lbfmodel/lbfmodel.yaml"};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
};

#endif
