/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Apr 17 19:21:21 2025


#include "HaarDetector_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(HaarDetectorParamsCOMPONENT, "yarp.device.HaarDetector")
}


HaarDetector_ParamsParser::HaarDetector_ParamsParser()
{
}


std::vector<std::string> HaarDetector_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("xmlCascade");
    params.push_back("lbfModel");
    return params;
}


bool      HaarDetector_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(HaarDetectorParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter xmlCascade
    {
        if (config.check("xmlCascade"))
        {
            m_xmlCascade = config.find("xmlCascade").asString();
            yCInfo(HaarDetectorParamsCOMPONENT) << "Parameter 'xmlCascade' using value:" << m_xmlCascade;
        }
        else
        {
            yCInfo(HaarDetectorParamsCOMPONENT) << "Parameter 'xmlCascade' using DEFAULT value:" << m_xmlCascade;
        }
        prop_check.unput("xmlCascade");
    }

    //Parser of parameter lbfModel
    {
        if (config.check("lbfModel"))
        {
            m_lbfModel = config.find("lbfModel").asString();
            yCInfo(HaarDetectorParamsCOMPONENT) << "Parameter 'lbfModel' using value:" << m_lbfModel;
        }
        else
        {
            yCInfo(HaarDetectorParamsCOMPONENT) << "Parameter 'lbfModel' using DEFAULT value:" << m_lbfModel;
        }
        prop_check.unput("lbfModel");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(HaarDetectorParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(HaarDetectorParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      HaarDetector_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: HaarDetector\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'xmlCascade': Haar cascade model file\n");
    doc = doc + std::string("'lbfModel': LBF model file\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device HaarDetector --xmlCascade haarcascade_frontalface_alt.xml --lbfModel lbfmodel/lbfmodel.yaml\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device HaarDetector\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
