#ifndef __YARP_CLOUD_UTILS_LOG_COMPONENT_HPP__
#define __YARP_CLOUD_UTILS_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(YCU)

#endif // __YARP_CLOUD_UTILS_LOG_COMPONENT_HPP__
