// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "humanoid_shm.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* M3HumanoidShmStatus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  M3HumanoidShmStatus_reflection_ = NULL;
const ::google::protobuf::Descriptor* M3HumanoidShmCommand_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  M3HumanoidShmCommand_reflection_ = NULL;
const ::google::protobuf::Descriptor* M3HumanoidShmParam_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  M3HumanoidShmParam_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_humanoid_5fshm_2eproto() {
  protobuf_AddDesc_humanoid_5fshm_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "humanoid_shm.proto");
  GOOGLE_CHECK(file != NULL);
  M3HumanoidShmStatus_descriptor_ = file->message_type(0);
  static const int M3HumanoidShmStatus_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3HumanoidShmStatus, base_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3HumanoidShmStatus, test_),
  };
  M3HumanoidShmStatus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      M3HumanoidShmStatus_descriptor_,
      M3HumanoidShmStatus::default_instance_,
      M3HumanoidShmStatus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3HumanoidShmStatus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3HumanoidShmStatus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(M3HumanoidShmStatus));
  M3HumanoidShmCommand_descriptor_ = file->message_type(1);
  static const int M3HumanoidShmCommand_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3HumanoidShmCommand, test_),
  };
  M3HumanoidShmCommand_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      M3HumanoidShmCommand_descriptor_,
      M3HumanoidShmCommand::default_instance_,
      M3HumanoidShmCommand_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3HumanoidShmCommand, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3HumanoidShmCommand, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(M3HumanoidShmCommand));
  M3HumanoidShmParam_descriptor_ = file->message_type(2);
  static const int M3HumanoidShmParam_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3HumanoidShmParam, test_),
  };
  M3HumanoidShmParam_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      M3HumanoidShmParam_descriptor_,
      M3HumanoidShmParam::default_instance_,
      M3HumanoidShmParam_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3HumanoidShmParam, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(M3HumanoidShmParam, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(M3HumanoidShmParam));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_humanoid_5fshm_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    M3HumanoidShmStatus_descriptor_, &M3HumanoidShmStatus::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    M3HumanoidShmCommand_descriptor_, &M3HumanoidShmCommand::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    M3HumanoidShmParam_descriptor_, &M3HumanoidShmParam::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_humanoid_5fshm_2eproto() {
  delete M3HumanoidShmStatus::default_instance_;
  delete M3HumanoidShmStatus_reflection_;
  delete M3HumanoidShmCommand::default_instance_;
  delete M3HumanoidShmCommand_reflection_;
  delete M3HumanoidShmParam::default_instance_;
  delete M3HumanoidShmParam_reflection_;
}

void protobuf_AddDesc_humanoid_5fshm_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_component_5fbase_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022humanoid_shm.proto\032\024component_base.pro"
    "to\"@\n\023M3HumanoidShmStatus\022\033\n\004base\030\001 \001(\0132"
    "\r.M3BaseStatus\022\014\n\004test\030\002 \001(\001\"$\n\024M3Humano"
    "idShmCommand\022\014\n\004test\030\001 \001(\001\"\"\n\022M3Humanoid"
    "ShmParam\022\014\n\004test\030\001 \001(\001B\002H\001", 186);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "humanoid_shm.proto", &protobuf_RegisterTypes);
  M3HumanoidShmStatus::default_instance_ = new M3HumanoidShmStatus();
  M3HumanoidShmCommand::default_instance_ = new M3HumanoidShmCommand();
  M3HumanoidShmParam::default_instance_ = new M3HumanoidShmParam();
  M3HumanoidShmStatus::default_instance_->InitAsDefaultInstance();
  M3HumanoidShmCommand::default_instance_->InitAsDefaultInstance();
  M3HumanoidShmParam::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_humanoid_5fshm_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_humanoid_5fshm_2eproto {
  StaticDescriptorInitializer_humanoid_5fshm_2eproto() {
    protobuf_AddDesc_humanoid_5fshm_2eproto();
  }
} static_descriptor_initializer_humanoid_5fshm_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int M3HumanoidShmStatus::kBaseFieldNumber;
const int M3HumanoidShmStatus::kTestFieldNumber;
#endif  // !_MSC_VER

M3HumanoidShmStatus::M3HumanoidShmStatus()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void M3HumanoidShmStatus::InitAsDefaultInstance() {
  base_ = const_cast< ::M3BaseStatus*>(&::M3BaseStatus::default_instance());
}

M3HumanoidShmStatus::M3HumanoidShmStatus(const M3HumanoidShmStatus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void M3HumanoidShmStatus::SharedCtor() {
  _cached_size_ = 0;
  base_ = NULL;
  test_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

M3HumanoidShmStatus::~M3HumanoidShmStatus() {
  SharedDtor();
}

void M3HumanoidShmStatus::SharedDtor() {
  if (this != default_instance_) {
    delete base_;
  }
}

void M3HumanoidShmStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* M3HumanoidShmStatus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return M3HumanoidShmStatus_descriptor_;
}

const M3HumanoidShmStatus& M3HumanoidShmStatus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_humanoid_5fshm_2eproto();  return *default_instance_;
}

M3HumanoidShmStatus* M3HumanoidShmStatus::default_instance_ = NULL;

M3HumanoidShmStatus* M3HumanoidShmStatus::New() const {
  return new M3HumanoidShmStatus;
}

void M3HumanoidShmStatus::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_base()) {
      if (base_ != NULL) base_->::M3BaseStatus::Clear();
    }
    test_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool M3HumanoidShmStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .M3BaseStatus base = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_base()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_test;
        break;
      }
      
      // optional double test = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_test:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &test_)));
          set_has_test();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void M3HumanoidShmStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .M3BaseStatus base = 1;
  if (has_base()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->base(), output);
  }
  
  // optional double test = 2;
  if (has_test()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->test(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* M3HumanoidShmStatus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .M3BaseStatus base = 1;
  if (has_base()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->base(), target);
  }
  
  // optional double test = 2;
  if (has_test()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->test(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int M3HumanoidShmStatus::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .M3BaseStatus base = 1;
    if (has_base()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->base());
    }
    
    // optional double test = 2;
    if (has_test()) {
      total_size += 1 + 8;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void M3HumanoidShmStatus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const M3HumanoidShmStatus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const M3HumanoidShmStatus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void M3HumanoidShmStatus::MergeFrom(const M3HumanoidShmStatus& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_base()) {
      mutable_base()->::M3BaseStatus::MergeFrom(from.base());
    }
    if (from.has_test()) {
      set_test(from.test());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void M3HumanoidShmStatus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void M3HumanoidShmStatus::CopyFrom(const M3HumanoidShmStatus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool M3HumanoidShmStatus::IsInitialized() const {
  
  return true;
}

void M3HumanoidShmStatus::Swap(M3HumanoidShmStatus* other) {
  if (other != this) {
    std::swap(base_, other->base_);
    std::swap(test_, other->test_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata M3HumanoidShmStatus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = M3HumanoidShmStatus_descriptor_;
  metadata.reflection = M3HumanoidShmStatus_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int M3HumanoidShmCommand::kTestFieldNumber;
#endif  // !_MSC_VER

M3HumanoidShmCommand::M3HumanoidShmCommand()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void M3HumanoidShmCommand::InitAsDefaultInstance() {
}

M3HumanoidShmCommand::M3HumanoidShmCommand(const M3HumanoidShmCommand& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void M3HumanoidShmCommand::SharedCtor() {
  _cached_size_ = 0;
  test_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

M3HumanoidShmCommand::~M3HumanoidShmCommand() {
  SharedDtor();
}

void M3HumanoidShmCommand::SharedDtor() {
  if (this != default_instance_) {
  }
}

void M3HumanoidShmCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* M3HumanoidShmCommand::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return M3HumanoidShmCommand_descriptor_;
}

const M3HumanoidShmCommand& M3HumanoidShmCommand::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_humanoid_5fshm_2eproto();  return *default_instance_;
}

M3HumanoidShmCommand* M3HumanoidShmCommand::default_instance_ = NULL;

M3HumanoidShmCommand* M3HumanoidShmCommand::New() const {
  return new M3HumanoidShmCommand;
}

void M3HumanoidShmCommand::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    test_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool M3HumanoidShmCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double test = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &test_)));
          set_has_test();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void M3HumanoidShmCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional double test = 1;
  if (has_test()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->test(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* M3HumanoidShmCommand::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional double test = 1;
  if (has_test()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->test(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int M3HumanoidShmCommand::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional double test = 1;
    if (has_test()) {
      total_size += 1 + 8;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void M3HumanoidShmCommand::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const M3HumanoidShmCommand* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const M3HumanoidShmCommand*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void M3HumanoidShmCommand::MergeFrom(const M3HumanoidShmCommand& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_test()) {
      set_test(from.test());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void M3HumanoidShmCommand::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void M3HumanoidShmCommand::CopyFrom(const M3HumanoidShmCommand& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool M3HumanoidShmCommand::IsInitialized() const {
  
  return true;
}

void M3HumanoidShmCommand::Swap(M3HumanoidShmCommand* other) {
  if (other != this) {
    std::swap(test_, other->test_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata M3HumanoidShmCommand::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = M3HumanoidShmCommand_descriptor_;
  metadata.reflection = M3HumanoidShmCommand_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int M3HumanoidShmParam::kTestFieldNumber;
#endif  // !_MSC_VER

M3HumanoidShmParam::M3HumanoidShmParam()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void M3HumanoidShmParam::InitAsDefaultInstance() {
}

M3HumanoidShmParam::M3HumanoidShmParam(const M3HumanoidShmParam& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void M3HumanoidShmParam::SharedCtor() {
  _cached_size_ = 0;
  test_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

M3HumanoidShmParam::~M3HumanoidShmParam() {
  SharedDtor();
}

void M3HumanoidShmParam::SharedDtor() {
  if (this != default_instance_) {
  }
}

void M3HumanoidShmParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* M3HumanoidShmParam::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return M3HumanoidShmParam_descriptor_;
}

const M3HumanoidShmParam& M3HumanoidShmParam::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_humanoid_5fshm_2eproto();  return *default_instance_;
}

M3HumanoidShmParam* M3HumanoidShmParam::default_instance_ = NULL;

M3HumanoidShmParam* M3HumanoidShmParam::New() const {
  return new M3HumanoidShmParam;
}

void M3HumanoidShmParam::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    test_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool M3HumanoidShmParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double test = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &test_)));
          set_has_test();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void M3HumanoidShmParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional double test = 1;
  if (has_test()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->test(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* M3HumanoidShmParam::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional double test = 1;
  if (has_test()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->test(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int M3HumanoidShmParam::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional double test = 1;
    if (has_test()) {
      total_size += 1 + 8;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void M3HumanoidShmParam::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const M3HumanoidShmParam* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const M3HumanoidShmParam*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void M3HumanoidShmParam::MergeFrom(const M3HumanoidShmParam& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_test()) {
      set_test(from.test());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void M3HumanoidShmParam::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void M3HumanoidShmParam::CopyFrom(const M3HumanoidShmParam& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool M3HumanoidShmParam::IsInitialized() const {
  
  return true;
}

void M3HumanoidShmParam::Swap(M3HumanoidShmParam* other) {
  if (other != this) {
    std::swap(test_, other->test_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata M3HumanoidShmParam::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = M3HumanoidShmParam_descriptor_;
  metadata.reflection = M3HumanoidShmParam_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
