/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Apr 17 19:21:21 2025


#include "QrDetector_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(QrDetectorParamsCOMPONENT, "yarp.device.QrDetector")
}


QrDetector_ParamsParser::QrDetector_ParamsParser()
{
}


std::vector<std::string> QrDetector_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("epsX");
    params.push_back("epsY");
    return params;
}


bool      QrDetector_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(QrDetectorParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter epsX
    {
        if (config.check("epsX"))
        {
            m_epsX = config.find("epsX").asFloat64();
            yCInfo(QrDetectorParamsCOMPONENT) << "Parameter 'epsX' using value:" << m_epsX;
        }
        else
        {
            yCInfo(QrDetectorParamsCOMPONENT) << "Parameter 'epsX' using DEFAULT value:" << m_epsX;
        }
        prop_check.unput("epsX");
    }

    //Parser of parameter epsY
    {
        if (config.check("epsY"))
        {
            m_epsY = config.find("epsY").asFloat64();
            yCInfo(QrDetectorParamsCOMPONENT) << "Parameter 'epsY' using value:" << m_epsY;
        }
        else
        {
            yCInfo(QrDetectorParamsCOMPONENT) << "Parameter 'epsY' using DEFAULT value:" << m_epsY;
        }
        prop_check.unput("epsY");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(QrDetectorParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(QrDetectorParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      QrDetector_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: QrDetector\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'epsX': eps used during horizontal scan of QR code stop marker detection\n");
    doc = doc + std::string("'epsY': eps used during vertical scan of QR code stop marker detection\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device QrDetector --epsX 0.0 --epsY 0.0\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device QrDetector\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
