/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Apr 17 19:21:21 2025


#ifndef QRDETECTOR_PARAMSPARSER_H
#define QRDETECTOR_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class QrDetector.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value | Required | Description                                                      | Notes |
* |:----------:|:--------------:|:------:|:-----:|:-------------:|:--------:|:----------------------------------------------------------------:|:-----:|
* | -          | epsX           | double | -     | 0.0           | 0        | eps used during horizontal scan of QR code stop marker detection | -     |
* | -          | epsY           | double | -     | 0.0           | 0        | eps used during vertical scan of QR code stop marker detection   | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device QrDetector --epsX 0.0 --epsY 0.0
* \endcode
*
* \code{.unparsed}
* yarpdev --device QrDetector
* \endcode
*
*/

class QrDetector_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    QrDetector_ParamsParser();
    ~QrDetector_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"QrDetector"};
    const std::string m_device_name = {"QrDetector"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 1;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    const std::string m_epsX_defaultValue = {"0.0"};
    const std::string m_epsY_defaultValue = {"0.0"};

    double m_epsX = {0.0};
    double m_epsY = {0.0};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
};

#endif
