name: Docker

on:
  workflow_dispatch:
    inputs:
      ubuntu:
        description: 'Ubuntu version'
        required: true
        default: '26.04'
        type: string
      opencv:
        description: 'OpenCV branch/tag'
        required: true
        default: '5.x'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  docker:
    name: build (ubuntu-${{inputs.ubuntu}}, opencv-${{inputs.opencv}})
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Check out main project
      uses: actions/checkout@v7

    - name: Log in to the Container Registry
      uses: docker/login-action@v4
      with:
        registry: ${{env.REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        push: true
        context: docker
        tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:ubuntu-${{inputs.ubuntu}}-opencv-${{inputs.opencv}}
        labels: ${{steps.meta.outputs.labels}}
        build-args: |
          OPENCV_TAG=${{inputs.opencv}}
          UBUNTU_TAG=${{inputs.ubuntu}}
