name: Docker

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  docker:
    name: build (ubuntu-${{matrix.system.ubuntu}}, opencv-${{matrix.opencv}})
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        system:
        # https://github.com/roboticslab-uc3m/questions-and-answers/issues/101
        - { ubuntu: '22.04', gcc: g++-11, clang: clang-15 }
        - { ubuntu: '24.04', gcc: g++-13, clang: clang-18 }
        opencv: ['4.x']

    steps:
    - name: Check out main project
      uses: actions/checkout@v4

    - name: Log in to the Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{env.REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: docker
        tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:ubuntu-${{matrix.system.ubuntu}}-opencv-${{matrix.opencv}}
        labels: ${{steps.meta.outputs.labels}}
        build-args: |
          OPENCV_TAG=${{matrix.opencv}}
          UBUNTU_TAG=${{matrix.system.ubuntu}}
          GCC_TAG=${{matrix.system.gcc}}
          CLANG_TAG=${{matrix.system.clang}}
