name: Docker

on:
  workflow_dispatch:
    inputs:
      ubuntu-tag:
        description: 'The Ubuntu tag to use for the Docker image'
        required: true
        type: choice
        options:
        - '20.04'
        - '22.04'
      opencv-tag:
        description: 'The OpenCV tag to use for the Docker image'
        required: true
        type: choice
        options:
        - '3.4'
        - '4.x'
        - '5.x'

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out main project
      uses: actions/checkout@v4

    - name: Log in to the Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{env.REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: vision:ubuntu-${{inputs.ubuntu-tag}}
        context: docker
        build-args: |
          OPENCV_TAG=${{inputs.opencv-tag}}
          UBUNTU_TAG=${{inputs.ubuntu-tag}}
